---
- include_tasks: configure_kernel.yml
  when: configure_kernel == true

- include_tasks: bind_drivers.yml
  when: bind_drivers == true

- include_tasks: set_ovs_dpdk.yml
  when: set_ovs_dpdk == true
