- fail: msg="no pci adress is defined"
  when: "pci_addresses | length == 0"

- name: unset dpdk-init
  command: "ovs-vsctl remove open_vswitch . other_config dpdk-init"

- name: set pmd-cpu-mask
  command: "ovs-vsctl remove open_vswitch . other_config pmd-cpu-mask"

- name: set dpdk lcore mask
  command: "ovs-vsctl remove open_vswitch . other_config dpdk-lcore-mask"

- name: unset dpdk socket memory
  command: "ovs-vsctl remove open_vswitch . other_config dpdk-socket-mem"

- name: restart openvswitch service
  service:
    name: openvswitch
    state: restarted

- set_fact: "network_driver={{ pci_addresses | get_kernel_driver}}"

- name: bind nics back to network driver
  command: "driverctl -v set-override {{ item }} {{ network_driver }}"
  with_items: "{{ pci_addresses }}"
  register: bind_regular



